branches:
  only:
    - master

cache:
  directories:
  - $HOME/.portage-pkgdir

matrix:
  include:
    - if: type = pull_request
      os: linux
      services: docker
      language: generic
      sudo: required
      script: ./tests/repoman.sh
    - if: type = pull_request
      os: linux
      services: docker
      language: generic
      sudo: required
      script: ./tests/emerge-new-or-changed-ebuilds.sh
    - if: type = cron
      os: linux
      services: docker
      language: generic
      sudo: required
      script: ./tests/newversioncheck.sh
    - if: type = cron
      os: linux
      services: docker
      language: generic
      sudo: required
      script: ./tests/emerge-random-ebuild.sh
    - if: type = cron
      os: linux
      services: docker
      language: generic
      sudo: required
      script: ./tests/emerge-random-live-ebuild.sh
