branches:
  only:
    - master

cache:
  directories:
  - $HOME/.portage-pkgdir

matrix:
  include:
    - os: linux
      services: docker
      language: generic
      sudo: required
      script:
        - 'if [ "${TRAVIS_EVENT_TYPE}" != "cron" ]; then
          ./tests/repoman.sh; fi'
    - os: linux
      services: docker
      language: generic
      sudo: required
      script:
        - 'if [ "${TRAVIS_EVENT_TYPE}" != "cron" ] && [ "${TRAVIS_PULL_REQUEST}" != "false" ] ; then
          ./tests/emerge-new-or-changed-ebuilds.sh; fi'
    - os: linux
      env: BUILD_TYPE=newversioncheck # marker environment variable to make the build matrix more readable in the UI
      services: docker
      language: generic
      sudo: required
      script:
        - 'if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then
          ./tests/newversioncheck.sh; fi'
    - os: linux
      services: docker
      language: generic
      sudo: required
      script:
        - 'if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then
          ./tests/emerge-random-ebuild.sh; fi'
