branches:
  only:
    - master

cache:
  directories:
  - $HOME/.portage-pkgdir

jobs:
  include:
    - if: type = pull_request
      os: linux
      services: docker
      language: generic
      sudo: required
      script: ./tests/repoman.sh
    - if: type = pull_request
      os: linux
      services: docker
      language: generic
      sudo: required
      script: ./tests/emerge-new-or-changed-ebuilds.sh
    - if: type != pull_request AND type != cron
      os: linux
      services: docker
      language: generic
      sudo: required
      script: ./docs/generate-site.sh
      deploy:
        provider: pages
        skip-cleanup: true
        local-dir: docs/site
        github-token: $GITHUB_API_TOKEN
        target-branch: gh-pages
        keep-history: false
    - if: type = cron
      os: linux
      services: docker
      language: generic
      sudo: required
      script: ./tests/newversioncheck.sh
    - if: type = cron
      os: linux
      services: docker
      language: generic
      sudo: required
      script: ./tests/emerge-random-ebuild.sh
